# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['word', 'text', 'author']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='learner',
            old_name='vocab_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='learner',
            old_name='words_perday',
            new_name='words_perDay',
        ),
        migrations.AddField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
