# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0002_auto_20161108_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('defn', models.TextField()),
                ('exmp', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='word',
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mords_api.Book'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mords_api.Word'),
        ),
        migrations.AddField(
            model_name='entry',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mords_api.Book'),
        ),
    ]
