# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0005_learner_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='pic',
            field=models.ImageField(blank=True, upload_to='mords/profile_images'),
        ),
    ]
