# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0007_auto_20161208_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mords_api.Word'),
        ),
    ]
