# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0008_auto_20161208_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='word',
        ),
    ]
