# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0009_auto_20161208_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['word']},
        ),
        migrations.AddField(
            model_name='entry',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
