# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0012_word_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
