# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0018_auto_20161209_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='defn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exmp',
            field=models.TextField(default=''),
        ),
    ]
