# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0019_auto_20161209_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_info_get',
            field=models.BooleanField(default=False),
        ),
    ]
