# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0020_word_is_info_get'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.PositiveIntegerField(default=3)),
                ('updated_date', models.DateTimeField()),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mords_api.Learner')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mords_api.Word')),
            ],
        ),
    ]
