# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0021_learningword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningword',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
