# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0022_auto_20161212_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningword',
            name='update_date',
            field=models.DateField(),
        ),
    ]
