# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mords_api', '0024_auto_20161212_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningword',
            name='update_date',
        ),
        migrations.AddField(
            model_name='learningword',
            name='update_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
